name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@master
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        node-version: '16'
        username: 'MuttonYung'
        reponame: 'MuttonYung.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}